# Generated by Django 3.0.3 on 2021-10-08 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True, verbose_name='Название задания')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка на раздел')),
                ('status', models.IntegerField(choices=[(1, 'Новое'), (2, 'Готово')], default=1, verbose_name='Статус задания')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('currency', models.TextField(blank=True, null=True, verbose_name='Валюта')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка на объявление')),
                ('published_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aparser.Task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
