# Generated by Django 3.0.3 on 2021-10-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0006_auto_20211016_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_dir',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='КатегорияEN'),
        ),
    ]
