# Generated by Django 3.0.3 on 2021-10-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0007_category_name_en_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Регион')),
                ('name_en_dir', models.CharField(blank=True, max_length=150, null=True, verbose_name='КатегорияEN')),
                ('JsId', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='JsonKey')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
    ]
