# Generated by Django 3.0.3 on 2021-10-16 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0008_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Населенные пункты')),
                ('name_en_dir', models.CharField(blank=True, max_length=150, null=True, verbose_name='Населенные пунктыEN')),
                ('JsId', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='JsonKey')),
                ('parent_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aparser.Region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенные пункты',
            },
        ),
    ]
