# Generated by Django 3.2.7 on 2021-10-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0003_auto_20211010_2039'),
        ('aparser', '0009_city'),
    ]

    operations = [
    ]
