# Generated by Django 3.0.3 on 2021-10-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0009_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='parent_Id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Регион'),
        ),
    ]
