# Generated by Django 3.2.7 on 2021-10-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0010_auto_20211020_2025'),
        ('aparser', '0010_merge_0003_auto_20211010_2039_0009_city'),
    ]

    operations = [
    ]
